options:
  formatter: stylish

files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore:  'src/sass/libs/*/.*'

rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2

  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties: 2

  no-qualifying-elements: 0
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  bem-depth: 2
  border-zero: 0
  brace-style:
    - 2
    -
      brace-style: 1tbs
      allow-single-line: false

  clean-import-paths: 0
  empty-args: 0
  hex-length:
    - 1
    -
      style: short

  hex-notation:
    - 1
    -
      style: lowercase

  indentation:
    - 2
    -
      size: 2

  leading-zero:
      - 1
      -
        include: true

  nesting-depth:
    - 1
    -
      max-depth: 2

  property-sort-order: 0
  quotes:
    - 2
    -
      style: single

  shorthand-values: 0
  url-quotes: 0
  variable-for-property: 0
  zero-unit:
    - 2
    -
      include: false

  # Inner Spacing
  space-after-comma: 1
  space-before-colon:
    - 2
    -
      include: false

  space-after-colon:
    - 2
    - include: true

  space-before-brace:
    - 2
    -
      include: true

  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon:
    - 2
    -
      include: true

  final-newline: 0

  pseudo-element: 0